
#ifndef _VERSION_H_
#define _VERSION_H_

#define CW_VERSION_MAJOR 0
#define CW_VERSION_MINOR 245
#define CW_VERSION_RELEASE 0

#define STR(S) #S
#define XSTR(S) STR(S)

#define CW_VERSION_STR XSTR(CW_VERSION_MAJOR) "." XSTR(CW_VERSION_MINOR) "." XSTR(CW_VERSION_RELEASE)
#define CW_VERSION ((int(CW_VERSION_MAJOR)<<24) + (int(CW_VERSION_MINOR)<<16) + (int(CW_VERSION_RELEASE)<<8))
#define CW_VERSION_LONG CW_VERSION_MAJOR,CW_VERSION_MINOR,CW_VERSION_RELEASE,0

#define CW_PRODUCT_NAME "Car World"
#define CW_AUTHOR "Marcus Hewat"
#define CW_COPYRIGHT "Copyright © 2010 " CW_AUTHOR

#endif //_VERSION_H_
